# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=20)),
                ('password', models.CharField(db_column='password', max_length=20)),
                ('email', models.CharField(db_column='email', max_length=50, null=True)),
                ('sex', models.CharField(db_column='sex', max_length=5, null=True)),
                ('age', models.IntegerField(db_column='age', null=True)),
                ('body', models.TextField(db_column='body', null=True)),
                ('pic', models.ImageField(db_column='pic', null=True, upload_to='')),
                ('state', models.IntegerField(db_column='state')),
            ],
        ),
        migrations.CreateModel(
            name='User_collection',
            fields=[
                ('collection_id', models.AutoField(auto_created=True, db_column='collection_id', primary_key=True, serialize=False)),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_comment',
            fields=[
                ('user_comment_id', models.AutoField(auto_created=True, db_column='user_comment_id', primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(db_column='comment_time')),
                ('comment_body', models.TextField(db_column='comment_body')),
                ('order_id', models.IntegerField(db_column='order_id')),
                ('order_page_id', models.IntegerField(db_column='order_page_id')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_goods')),
                ('manage', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_email',
            fields=[
                ('email_id', models.AutoField(auto_created=True, db_column='email_id', primary_key=True, serialize=False)),
                ('email_time', models.DateTimeField(db_column='email_time')),
                ('email_body', models.TextField(db_column='email_body')),
                ('email_title', models.CharField(db_column='email_title', max_length=50)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
