# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_name', models.CharField(db_column='power_name', max_length=30)),
                ('power_url', models.CharField(db_column='power_url', max_length=50)),
                ('powe_namespace', models.CharField(db_column='power_namespace', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manage_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_column='role_name', max_length=20)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('add_user', models.CharField(db_column='add_user', max_length=30)),
                ('status', models.SmallIntegerField(db_column='status')),
                ('power', models.ManyToManyField(db_column='power_id', to='manageuser.Manage_power')),
            ],
        ),
    ]
