# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0002_manage_power_manage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='manage_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_role'),
        ),
    ]
