# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0003_manage_manage_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_role',
            name='power',
            field=models.ManyToManyField(to='manageuser.Manage_power'),
        ),
    ]
