# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageuser', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(auto_created=True, db_column='cart_id', primary_key=True, serialize=False)),
                ('goods_name', models.CharField(db_column='goods_name', max_length=100)),
                ('goods_pic', models.CharField(db_column='goods_pic', max_length=100)),
                ('goods_price', models.FloatField(db_column='goods_price')),
                ('goods_sum', models.FloatField(db_column='goods_sum')),
                ('goods_num', models.IntegerField(db_column='goods_num')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_goods')),
                ('manage', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage')),
                ('shop', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_shop')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
