# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageuser', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(auto_created=True, db_column='address_id', primary_key=True, serialize=False)),
                ('address_username', models.CharField(db_column='address_username', max_length=20)),
                ('address_phone', models.IntegerField(db_column='address_phone')),
                ('address_name', models.CharField(db_column='address_name', max_length=100)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_page',
            fields=[
                ('order_page_id', models.AutoField(auto_created=True, db_column='order_page_id', primary_key=True, serialize=False)),
                ('goods_name', models.CharField(db_column='goods_name', max_length=30)),
                ('goods_pic', models.CharField(db_column='goods_pic', max_length=100)),
                ('manage_price', models.FloatField(db_column='manage_price')),
                ('goods_sum', models.FloatField(db_column='goods_sum')),
                ('goods_num', models.IntegerField(db_column='goods_num')),
                ('order_number', models.CharField(db_column='order_number', max_length=30)),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_goods')),
                ('manage', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage')),
            ],
        ),
        migrations.CreateModel(
            name='Oreder',
            fields=[
                ('order_id', models.AutoField(auto_created=True, db_column='order_id', primary_key=True, serialize=False)),
                ('order_num', models.CharField(db_column='order_num', max_length=30)),
                ('order_time', models.DateTimeField(db_column='order_time')),
                ('send_time', models.DateTimeField(db_column='send_time')),
                ('recv_time', models.DateTimeField(db_column='recv_time')),
                ('order_sum', models.FloatField(db_column='order_sum')),
                ('order_state', models.IntegerField(db_column='order_state')),
                ('address', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.CASCADE, to='order.Address')),
                ('shop', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_shop')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='order_page',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.Oreder'),
        ),
        migrations.AddField(
            model_name='order_page',
            name='shop',
            field=models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='manageuser.Manage_shop'),
        ),
    ]
